services:
  qbit_benchmark:
    image: ghcr.io/xsaveopt/qbit_benchmark:latest
    container_name: qbit_benchmark
    restart: unless-stopped
    command: serve -size 4GiB -piece 1MiB -announce http://YOUR_HOST:6969/announce -o /out/qbench.torrent
    read_only: true
    volumes:
      - ./out:/out
    ports:
      - "6969:6969"
      - "6881:6881"
